server:
  port: 8080

spring:
  application:
    name: customer
  server:
    port: 8080
  spring:
    application:
      name: customer
    datasource:
      username: amigoscode
      url: jdbc:postgresql://localhost:5432/customer
      password: Dilshan1234/
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true
